name: first-github-action

on: [push, pull_request]

jobs:
  run-some-shell-commands:
    runs-on: ubuntu-18.04
    steps:
      - name: echo a string
        run: echo Hello Searching...
      - name: multiple commands
        run: |
          npm -v
          node -v
      - name: python script
        run: |
          import platform
          print (platform.processor())
        shell: python