name: first-github-action

on: [push]

jobs:
  run-shell-commands:
    runs-on: self-hosted
    steps:
      - name: echo a string
        run: echo Hello Searching...
      - name: multiple commands
        run: |
          npm -v
          node -v
      - name: python script
        run: |
          import platform
          print (platform.processor())
        shell: python